CC = gcc

build: reverse_word_while_loop.c reverse_word_for_loop.c
	$(CC) reverse_word_for_loop.c -o reverse_word_for_loop
	$(CC) reverse_word_while_loop.c -o reverse_word_while_loop

clean:
	erase *.exe